### ISSUE TITLE
Textra shortcuts don't work with Nova

### ISSUE THREAD

**Issue by RedWolf1910** [BranchMetrics/sesame_issues#199] opened 2020-06-15 18:03 UTC
Sesame doesn't recognize Textra shortcuts with Nova Launcher.
Addon for message shortcuts bought, but nothing happens.

**Comment by philwall2** [comment] 2020-06-17 20:43
Hey @RedWolf1910 Textra is super weird. For years now some users report the app disappears, some of the shortcuts work, others don't. We can't reproduce any of these issues on our test devices

We've looked into it several times and the best we can tell is Textra is pushing several different versions of their app to different users (almost like an A/B test). And some of these versions break shortcuts.

Unfortunately, there's nothing we can do about it. I'm going to close this ticket b/c we've investigated it several times before. I wish I had a better result for you :(

**Closed as completed by philwall2** 2020-06-17 20:43 UTC
