### ISSUE TITLE
Shortcut to WhatsApp Contacts not Updated Properly

### ISSUE THREAD

**Issue by risalabdilah** [BranchMetrics/sesame_issues#162] opened 2020-03-05 01:46 UTC
Hi I'm Risal,
Please help to check the feature of WhatsApp Contacts Shortcut, because it seems that it wouldn't update the shortcut properly.
The new contacts that have been added are not showing as I type their name on App Search.

I did try to "Refresh all shortcut data" couple times, and it still doesn't work.
There were 992 shortcut for WhatsApp and didn't change at all as I refresh it.

I'm using Redmi Note 4 Mediatek version and still running on Android 6.
Please inform me the update at risalabdilah@gmail.com

Thanks in advance

**Comment by philwall2** [comment] 2020-03-05 17:27
When you go to Sesame Settings > Shortcuts > WhatsApp... do you see them listed there? If so would you mind take a screenshot of that screen, then one of you searching where the results doesn't show? Thanks,

**Comment by risalabdilah** [comment] 2020-03-06 02:21
So I've been added "Kang Fiesta"s number about 3 months ago.
Yet the WhatsApp shortcut won't show up until now when I type his name, but the Telegram shortcut is fine.

These are the screenshots for the case
1st, when I type "Fiesta"
2nd, there is no "Kang Fiesta" among other "Kang..."
3rd, "Kang" is just a title to call older people in Indonesia, similar to "Mr." anyway :D

Please help, thanks in advance

Attachment : 
1. ![WhatsApp Image 2020-03-06 at 09 11 36](https://user-images.githubusercontent.com/36788536/76044036-b6c9e900-5f8b-11ea-8b41-e87c533f15df.jpeg)
2. ![WhatsApp Image 2020-03-06 at 09 11 36 (1)](https://user-images.githubusercontent.com/36788536/76044072-cf3a0380-5f8b-11ea-93a5-7c9bb5083925.jpeg)

**Comment by risalabdilah** [comment] 2020-03-06 04:06
I mean this is not just happen to "Fiesta", all WhatsApp contacts I've been added recently are not showing up as I type their name too

**Comment by philwall2** [comment] 2020-03-06 17:12
Thanks for the screenshots. Since they aren't showing up in Sesame settings we can eliminate the bug being in Sesame Search. The bug must be in creating/saving the shortcuts

Can you try adding a shortcut again? What happens? Does it show up in the list in Settings > Shortcuts > WhatsApp? Does it then disappear from that list?

**Comment by risalabdilah** [comment] 2020-03-06 17:46
I tried to manually Add WhatsApp shortcut for Fiesta, and yes, he's appear in the App Search.

But did you mean that I have to manually add the shortcut? 
I guess all the shortcut for WhatsApp contacts are automatically added, just like the Telegram ones

I mean there are a lot of contacts that I have to manually added if the only way is to manually add the shortcut
I hope it was a bug and can be fixed

**Comment by philwall2** [comment] 2020-03-06 20:09
Ah, OK. That means that in your Contacts DB these contacts aren't being listed as "WhatsApp Contacts". Sorry about that, the Contacts DB data is super messy.

We added the option to manually create them in order to get around this limitation.

You could try using the Contact Actions Add-on. We use a slightly different method for that feature. If it doesn't work, I'd be happy to give you a refund.

Going to close this as it's not a bug.

**Closed as completed by philwall2** 2020-03-06 20:09 UTC
