### ISSUE TITLE
Shortcuts still not working on Android

### ISSUE THREAD

**Issue by googlinggreg** [BranchMetrics/sesame_issues#152] opened 2020-01-17 09:33 UTC
It's been almost a week and the shortcuts still aren't working on Android for the beta. This is already documented on reddit. App search still works, but shortcuts disappear as soon as you begin typing.

**Comment by philwall2** [comment] 2020-01-17 16:54
Do you mean[ this post](https://www.reddit.com/r/sesame/comments/el6l7d/sesame_search_broken_on_android/)? 

I might be misunderstanding but it seems like they're saying "I don't see contact actions like Phone, SMS, and Email". Is that the same bug you're seeing?

We put a fix in for that about a week ago and thought everything was OK. What bug are you seeing exactly? Can you provide some detail on how to reproduce it? Thanks.

**Comment by googlinggreg** [comment] 2020-01-17 17:59
It's like that bug, except not even whatsapp contacts or other shortcuts
will show up once you start typing.

**Comment by philwall2** [comment] 2020-01-18 00:04
OK, let's figure it out.

First, is Sesame reading your Contacts? Go to Sesame Settings > Shortcuts > Contacts, you should see all your contacts listed. If you aren't try the "Show hidden contacts" option above on that same screen.

If that doesn't fix it can you: verify you're on the latest version of Sesame, send me a screenshot of your contacts settings screen and Sesame search?

Thanks!

**Comment by googlinggreg** [comment] 2020-01-18 00:18
Didn't fix it. Not sure exactly what screenshot you need, but let me know
if you need more.

**Comment by okjed** [comment] 2020-01-20 17:50
> Do you mean[ this post](https://www.reddit.com/r/sesame/comments/el6l7d/sesame_search_broken_on_android/)?
> 
> I might be misunderstanding but it seems like they're saying "I don't see contact actions like Phone, SMS, and Email". Is that the same bug you're seeing?
> 
> We put a fix in for that about a week ago and thought everything was OK. What bug are you seeing exactly? Can you provide some detail on how to reproduce it? Thanks.

What is the fix for this - not having contacts show up? I just purchased the add-on as well, just in case and to show support -- and still don't have contacts showing.

**Comment by mattfwb** [comment] 2020-01-21 14:32
@googlinggreg do you mean this?:

When using the widget to start the search I can see the shortcuts initially. As soon as I type, only the app search and web search results show, none of the shortcuts. Screenshots below.
If I do the search from the app drawer then it functions as expected and I can see the shortcut results (from WhatsApp, YouTube, etc.)

Android 10, OnePlus 6, latest Sesame beta.

![Screenshot_20200121-161959~2](https://user-images.githubusercontent.com/39420692/72813078-690f5080-3c6b-11ea-91bb-0598f0f5c8f9.jpg)

![Screenshot_20200121-162016~2](https://user-images.githubusercontent.com/39420692/72813084-70cef500-3c6b-11ea-9af6-e425f15d7221.jpg)

**Comment by googlinggreg** [comment] 2020-01-21 15:10
Yes, that's the problem.

**Comment by mattfwb** [comment] 2020-01-21 15:37
@philwall2 is there anything I can do to help diagnose the problem?

**Comment by philwall2** [comment] 2020-01-22 03:24
Hey everyone. It seems like we are talking about 2 bugs here.

1. In the Reddit link you shared. That seems to be a bug with Contact Actions where when you type your contact shortcuts don't show up. We pushed a fix for this in the latest release and as far as I can tell that worked. If you are still seeing this problem go to Sesame Settings > Shortcuts > Contacts > and tap to "Show hidden contacts".

2. Is a bug where when you type **no shortcuts show up**. @mattfwb this looks like what you are reporting. **Q1**: are you on the Beta? **Q2** If you are on the Beta try going to Sesame Settings > Settings > Debug > and turn OFF "Optimized Search". Does that fix it? 

@googlinggreg which bug does it sound like you have? The key difference is whether you see any shortcuts at all when you start typing.

**Comment by okjed** [comment] 2020-01-22 03:36
>     2. Is a bug where when you type **no shortcuts show up**. @mattfwb this looks like what you are reporting. **Q1**: are you on the Beta? **Q2** If you are on the Beta try going to Sesame Settings > Settings > Debug > and turn OFF "Optimized Search". Does that fix it?

I just wanted to say -- turning off optimized search fixed my issues. I run the beta. If I did app search via Nova Launcher (with the Sesame integration) all worked fine. If I launched Sesame Search, contacts did not work. After turning off optimized search, all seems good regardless of the way I launch the feature.

**Comment by philwall2** [comment] 2020-01-22 04:10
> > ```
> > 2. Is a bug where when you type **no shortcuts show up**. @mattfwb this looks like what you are reporting. **Q1**: are you on the Beta? **Q2** If you are on the Beta try going to Sesame Settings > Settings > Debug > and turn OFF "Optimized Search". Does that fix it?
> > ```
> 
> I just wanted to say -- turning off optimized search fixed my issues. I run the beta. If I did app search via Nova Launcher (with the Sesame integration) all worked fine. If I launched Sesame Search, contacts did not work. After turning off optimized search, all seems good regardless of the way I launch the feature.

@okjed this is helpful. It tells us that the new version of Search we built has a serious bug. Would you mind also following those 1, 2, 3 steps above and include "okjed" as the message? That will give us more data to ID the problem.

**Comment by okjed** [comment] 2020-01-22 20:21
> @okjed this is helpful. It tells us that the new version of Search we built has a serious bug. Would you mind also following those 1, 2, 3 steps above and include "okjed" as the message? That will give us more data to ID the problem.

I'm happy to provide more detail -- but I'm not certain what you're referring to as 1, 2, 3 steps above. Not seeing anything that matches that in this issue earlier in the thread.

**Comment by mattfwb** [comment] 2020-01-27 18:00
@philwall2 sorry for the delayed reply.

Issue is (2), and turning off optimised search solved the problem.

What can I provide you with? Like okjed, I'm not sure which 1,2,3 steps to follow.

**Comment by philwall2** [comment] 2020-01-28 03:15
@mattfwb and @okjed sorry, what I said was definitely confusing :)

Here's what would help

1. Turn back on Optimized Search (in Debug options)
2. Figure out something you can type that will trigger the bug. E.g. if you have Chrome installed and you type "chr" and get 0 results when optimized search is ON, that's what we're looking for
3. Go into Sesame Settings > Settings > Debug options > Tap to send debug data and include the message "optimized search breaks on chr"

That will send in your data and tell us exactly how to trigger the bug with it. Thanks!

**Comment by mattfwb** [comment] 2020-01-28 06:02
@philwall2 thanks, sent the debug data, included my username in the message. Let me know if you need more info.

**Comment by philwall2** [comment] 2020-01-30 15:46
@okjed @mattfwb , we pushed a fix to Beta (v3.6.2-beta4) that we think fixes the Optimized Search bug. Would you mind checking you're on the latest beta then turning back on Optimized search and seeing if it still crashes?

Thanks again for all your help.

**Comment by okjed** [comment] 2020-01-30 19:07
I missed the notification for your earlier message -- but did just now turn on Optimized Search again. Appears to be working perfectly in my checks so far.

**Comment by mattfwb** [comment] 2020-01-30 22:31
@philwall2 Yes, it has fixed the issue for me - thanks!!

**Comment by philwall2** [comment] 2020-01-31 03:50
Awesome! @okjed @mattfwb y'all helped out huge here. We wouldn't have been able to figure this out without your data.

FWIW the problem was that we moved to Native code to make search faster. People who had shortcut labels that were >128 characters broke our search because the Native code could support up to 255 characters but Java can support only 128 characters. When the Native code would translate shortcuts with > 128 characters to Java, it would break.

**Closed as completed by philwall2** 2020-01-31 03:50 UTC
