### ISSUE TITLE
Some apps are recognized as Reddit shortcuts

### ISSUE THREAD

**Issue by gofirst2220** [BranchMetrics/sesame_issues#75] opened 2019-06-04 14:27 UTC
I commented on other issue but it was closed so I am pasting it here.

Some apps like Adult Swim, ESPN, Discovery Go, Disney Go, etc., are recognized as Reddit apps so i ended up with subreddit shortcuts attached to them.

Uninstalling and reinstalling them, resetting Sesame, etc., did not fix it.

**Comment by philwall2** [comment] 2019-06-04 16:16
Hey, sorry about this but I'm not sure what we can do. The problem is we have Sesame set to send out an intent and ask Android "who can open this Reddit link?" We do that so we can support all the dozens of Reddit apps out there.

It seems like A) there's a mistake in how we're doing it, or B) there's some weird data state on your device where Android thinks these other apps open Reddit links.

Unfortunately, we can't reproduce the issue and when we checked our code it's pretty simple. I'm really sorry about this but if I'm being totally honest, this seems like a weird edge case / bad data state and the only thing that would fix it is to remove Reddit auto detection, which would take a big feature away from lots of users.

**Comment by gofirst2220** [comment] 2019-06-05 12:42
Well I didn't even set those apps as Reddit apps, only official app, Slide, and Boost are set as Reddit apps. so I don't know why it thinks ESPN, Disney Go, Discovery Go, Adult Swim, etc., are Reddit apps when they are not.

**Comment by philwall2** [comment] 2019-06-05 15:51
I know. It's not your fault. But what's happening is at some point those apps set themselves as able to open Reddit links. And since Sesame's detection is asking "can you open Reddit links?", it's recognizing them as Reddit apps.

The problem is there's no other way to detect Reddit apps (that we can think of). So it's either A) this bug happens every now and then, or B) we can't automatically support Reddit apps.

I'm going to close this issue. It's not because I don't care, but because there's no real solution.

**Closed as completed by philwall2** 2019-06-05 15:51 UTC
Labels: bug

**Comment by philwall2** [comment] 2019-06-05 16:14
To provide more of a solution... you can go into Sesame Settings > Shortcuts > ESPN, Disney etc and in the upper right Toggle OFF all shortcuts. That will remove them so you won't see the problem.

Again, I'm really sorry, I wish there was a clear fix here. LMK if you see something I'm missing.

EDIT: another thing you can try is going to Settings > Permissions and removing the Reddit connection, then re-adding it. That will re-trigger the detection. If those apps are no longer registering as Reddit apps, that might fix it.
