### ISSUE TITLE
The item that opens on "enter" is not the first result

### ISSUE THREAD

**Issue by rohit-gohri** [BranchMetrics/sesame_issues#83] opened 2019-06-27 03:28 UTC
Whenever I'll search for something and press enter it takes me to a result from the history of the search query. Like one of the first suggestions when I started typing.

For example: 
- I'll type "te", it'll give me a suggestion of "Telegram" at top. 
- Then I'll complete typing "testing something" and the first suggestion is now a Google Search Result which is what I want to do. 
- But pressing enter takes me to the old first suggestion, "Telegram". 

(I'll upload a video recording once I get access to my laptop)

**Comment by philwall2** [comment] 2019-06-27 16:05
Hey Rohit, the video will help. I tried to reproduce on my test devices and it seems to be working. Meaning it's opening the suggestion "testing something" when I hit enter.

**Comment by rohit-gohri** [comment] 2019-06-28 05:24
https://imgur.com/a/MENc3dP

I also noticed that there is a blank tile before the Google app suggestion. Could be that something else is affecting this.

#### Some other details:
* App Version: 3.5.2
* Android version: 9
* Device: Asus Max Pro M2 (ASUS_X01BDA)

**Comment by philwall2** [comment] 2019-06-28 14:13
Yeah, that phantom is definitely the problem. Any idea what that could be? Try toggling off QuickSearch apps in Search Settings.

It could be that Sesame is expecting an app there that you don't have installed. Weird.

**Comment by rohit-gohri** [comment] 2019-06-30 08:13
I was going to try that when I noticed that the phantom app disappeared. Could be some app that updated. And the issue is fixed now. 
The only app I remember recently uninstalling / reinstalling was Chrome.
Anyway, it's fixed now. Should I close the issue?

**Comment by philwall2** [comment] 2019-07-01 20:13
Ah good. I'll close it for you :)

Thanks for reporting though. It's very much appreciated.

**Closed as completed by philwall2** 2019-07-01 20:13 UTC
Labels: question
