### ISSUE TITLE
[Feature Request] Name for Chrome Shortcuts

### ISSUE THREAD

**Issue by arcanjoserra** [BranchMetrics/sesame_issues#123] opened 2019-10-06 19:52 UTC
After adding a Chrome Shortcut it goes like this on the search results: 

![photo_2019-10-06_16-50-54](https://user-images.githubusercontent.com/8283629/66274880-7db10f80-e859-11e9-8e32-96ee96b60bd0.jpg)

It'd be nice to be able to search for a **given name** rather than a link :)

**Comment by Kordian-Dziwisz** [comment] 2019-11-12 20:20
Isn't it a duplicate of #109 , check it

**Comment by philwall2** [comment] 2019-11-21 17:51
Mostly a duplicate of #109 but I get the difference and will keep it in mind. Thanks for the feedback.

**Closed as completed** 2019-11-21 17:50 UTC
