### ISSUE TITLE
Web search result always opened in Chrome and not default browser

### ISSUE THREAD

**Issue by mtalexan** [BranchMetrics/sesame_issues#180] opened 2020-04-10 17:59 UTC
If the `Search Engine` setting is set to a source that doesn't have a stand alone app installed (e.g. StartPage, DuckDuckGo), and the `Open Search Results With` option is set to `Search Engine`, results are always opened in Google Chrome regardless of what the default browser setting is.

A simple example:
1. Install Firefox, Brave, whatever
2. Set the new browser as your default
3. Set the Sesame setting for `Search Engine` to `StartPage`
4. Set the Sesame setting for `Open Search Results With` to `Search Engine`
5. Exit the setting
6. Start a Sesame Search
7. Type some random terms (e.g. "foo bar") and hit enter

Expected:
The default browser is opened to the Startpage search results.

Actual:
The Chrome Browser is opened to the Startpage search results.

With the current implementation, only Google and DuckDuckGo are effectively supported as search engines, and only if the DuckDuckGo browser is installed. This also isn't indicated anywhere.

**Comment by philwall2** [comment] 2020-04-13 18:29
Hey Mike, Sesame's not able to pick up which is the "default" browser. 

You'll need to specify which browser you want to open. Are you by chance hitting the enter key on your keyboard to launch the shortcut? If so, the enter key launches the first app listed in your QuickSearch order. 

By default, that's Chrome. You can change the ordering in Search Settings.

LMK if that was the issue.

**Comment by mtalexan** [comment] 2020-04-13 19:22
There were no applications listed when I started the search, only my search terms with an upper-right-pointing arrow. Clicking that entry versus hitting enter had no difference.

It's a little strange that Sesame has an  `Open Search Results With` option when the majority of search engines do not have an associated browser. Maybe it would make sense to have an option in that drop down to open with the default browser instead.

I believe a generic Intent can be sent to open a URL, and Android will feed that to the default browser. I don't think Sesame has to know exactly what browsers are installed on the system to pick the default browser for opening a URL.  For example, even my non-Gmail email application can trigger a new page in my default (non-Chrome) browser to be opened, and it definitely doesn't ask the system about what browsers are installed.

**Comment by philwall2** [comment] 2020-04-14 01:51
Drag the browser you want to the top of this list. Then when you hit Enter, Startpage will open in the browser of your choice.

![Screenshot_20200413-184943](https://user-images.githubusercontent.com/13373317/79177454-b1946100-7db7-11ea-880e-4e3dbb2b3019.png)

Tapping a suggestion will still open in Chrome. I'll ask Steve if there's a way around this.

**Comment by philwall2** [comment] 2020-04-14 02:07
Steve confirmed we are doing a check for the default browser. I put my settings how you laid them out in the bug report. Changed my default browser to FireFox. It all worked as expected (Firefox opened startpage.com).

Do change the order of your apps, because hitting the Enter key will open whatever is listed #1 there.

Going to close this now. LMK if there's still a reproduce-able bug on your end.

**Closed as completed by philwall2** 2020-04-14 02:07 UTC
