### ISSUE TITLE
Can't give a shortcut telephonenumber a name

### ISSUE THREAD

**Issue by hankkoopmans** [BranchMetrics/sesame_issues#176] opened 2020-04-06 19:22 UTC
When i make a shortcut to call a person i need to select his number, i can't select his name...

**Comment by philwall2** [comment] 2020-04-07 19:39
Are you talking about using the QuickSearch feature with the Phone Dialer? If so, the problem is Sesame hands the search query over to the phone and it chooses how to respond. Most Phones will automatically convert a text entry into numbers. 

I get that it's basically not functional but the problem is we can't control how they respond.

Closing this now. But let me know if I misunderstood.

**Closed as completed by philwall2** 2020-04-07 19:39 UTC
